### ISSUE TITLE
Joint probability of (circle, green)

### ISSUE THREAD

**Issue by skystrife** [smassung/text-data-book-comments#2]
In the probability and statistics chapter, I think you mean to say that the joint probability of (circle, green) is 1/6, not 1.

Generally speaking, I think using a non-uniform color distribution might make the example more illustrative (you can then have an example where it is 1/6, and an example where it isn't).

**Comment by smassung** [comment]
Good catch, that should be 1/6, not 1.

And yes, I can change to a non-uniform color distribution, probably by making two of the circles the same color.
