### ISSUE TITLE
Indentation after equations

### ISSUE THREAD

**Issue by skystrife** [smassung/text-data-book-comments#3]
It looks like, in some paragraphs, you've got indentation happening in text that is interspersed with equations where you probably don't mean to. If you only have a single line break in your LaTeX source (instead of a double), then the text won't be indented like a new paragraph. Look at the Bayes' rule section of the probability chapter to see what I'm talking about.

**Comment by smassung** [comment]
The "therefore" and "we" in the section 2.1.3 (Bayes' Rule) should be unindented, right? And there should also be some punctuation added.

**Comment by smassung** [comment]
I never realized this, but to not indent you can write text like this:

``` latex
We have the following equation,
%
$$\sum_{i=0}p(x_i|\theta)$$
%
which is easy to understand.
```

Note the comments.
