### ISSUE TITLE
Error: Wrong inequality symbol.

### ISSUE THREAD

**Issue by pauljurczak** [smassung/text-data-book-comments#5]
In Section 5.3 Document Selection vs Document Ranking on page 52 you wrote:
R'(q) = {d|f(q, d) ≤ θ}
but it should be:
R'(q) = {d|f(q, d) ≥ θ}
or:
R'(q) = {d|f(q, d) > θ}

**Comment by smassung** [comment]
Thanks! Just fixed it and reuploaded the pdf.
