### ISSUE TITLE
Typo in section 5.5

### ISSUE THREAD

**Issue by pauljurczak** [smassung/text-data-book-comments#7]
> The classic probabilistic model has led to the BM25 retrieval function (which we discussed in the vector space model), because its form is actually similar to a vector space model.

could be:

> The classic probabilistic model has led to the BM25 retrieval function (which we discussed in the vector space model, because its form is actually similar to a vector space model).

**Comment by smassung** [comment]
Thanks, I'll keep this open until my next round of edits on that chapter.
